---
- name: "extract artifact"
  shell: |
    mkdir /home/ubuntu/backend
    tar -xvf ~/project/artifact.tar.gz /home/ubuntu/backend
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
